In [2]:
import numpy as np
# try to do the original not numpy

In [3]:
#add
m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
]
# make it input type
m2 = [[9,8,7],
      [6,5,4],
      [3,2,1]
]
print(np.add(m1,m2))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
#multi
print(np.multiply(m1,m2))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [8]:
#transpose
trans = [[1,2],
         [3,4],
         [5,6]]
print(np.transpose(trans))

[[1 3 5]
 [2 4 6]]


In [ ]:
# matrix product